name: Run test and organize test coverage reports

on:
  workflow_call:
    inputs:
      run_e2e:
        description: "The testing type. In generally, it only has 2 options: 'unit-test' and 'integration-test'."
        type: boolean
        required: false
        default: false
      with-environment-variables:
        description: "Set the specific environment for the environment variables."
        type: string
        required: false
        default: ''
    secrets:
      e2e_test_api_token:
        description: "Set the Slack bot token for end-to-end test."
        required: false

jobs:
  run_unit-test:
#    name: Run all unit test items
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_uv_run_test.yaml@master
    with:
      test_type: unit-test
      test_folder: './test/unit_test'
      python-versions: '["3.13"]'
      operating-systems: '["ubuntu-latest", "ubuntu-22.04", "macos-latest", "macos-14"]'

  run_integration-test:
#    name: Run all integration test items
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_uv_run_test.yaml@master
    with:
      test_type: integration-test
      test_folder: './test/integration_test'
      python-versions: '["3.13"]'
      # Only run on Ubuntu - macOS doesn't have Docker available for Testcontainers
      operating-systems: '["ubuntu-latest", "ubuntu-22.04"]'

  unit-test_codecov:
#    name: For unit test, organize and generate the testing report and upload it to Codecov
    if: ${{
        contains(fromJSON('["pull_request","workflow_dispatch","schedule"]'), github.event_name) ||
        (github.event_name == 'push' && github.ref_name == 'master')
      }}
    needs: run_unit-test
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_organize_test_cov_reports.yaml@master
    with:
      test_type: unit-test

  integration-test_codecov:
#    name: For unit test, organize and generate the testing report and upload it to Codecov
    if: ${{
        contains(fromJSON('["pull_request","workflow_dispatch","schedule"]'), github.event_name) ||
        (github.event_name == 'push' && github.ref_name == 'master')
      }}
    needs: run_integration-test
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_organize_test_cov_reports.yaml@master
    with:
      test_type: integration-test

  all_test_codecov:
#    name: Organize and generate the testing report and upload it to Codecov
    if: ${{
          contains(fromJSON('["pull_request","workflow_dispatch","schedule"]'), github.event_name) ||
          (github.event_name == 'push' && github.ref_name == 'master')
      }}
    needs: [run_unit-test, run_integration-test]
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_organize_test_cov_reports.yaml@master
    with:
      test_type: all-test
